### Type of Arguments 

- 1. Required Positional Argument 
- 2. Default argument
- 3. Keyworded argument 
- 4. Variable length argument (*args)
- 5. Keyworded Variable length argument (*kwargs)

#### 1. Required Positional Argument 

- The number of variables inside the function declaration and the function call should be the same 
- The value passed from the argument are taken by the parameters
- It should be in a sequenece as they are positioned which means the order matters
- The variable in function call and in function declaration may be same or different, it doesn't matter

In [2]:
def add(x, y):
    print(x)
    print(y)
    c = x+y
    return c

add(1,3)

1
3


4

In [3]:
add(3,1)

3
1


4

In [4]:
add(1)

TypeError: add() missing 1 required positional argument: 'y'

In [5]:
add(1,2,3)

TypeError: add() takes 2 positional arguments but 3 were given

In [6]:
def add(x, y):
    print(x)
    print(y)
    c = x+y
    return c


x = 1
y = 2
add(x, y)

1
2


3

In [7]:
def add(x, y):
    print(x)
    print(y)
    c = x+y
    return c


a = 1
b = 2
add(a, b)

1
2


3

### 2. Default arguments 

- When we assign any value to a variable in the function declaration itself, it it becomes a default argument 
- If we dont pass any value for the default argument, then it will take the default value that we have already assigned while declaring or defining the function 
- If we pass any value to the default argument, then it will take the last assigned value 
- The number of variable passed as an argument can be equal to or less than the number of variable passed as parametrs
    - If the number of argument passed is less than the number of parametrs then it will take the default value that we have assigned default argument 
    - If the number of arguments are equal to the number of parameters then it will act as positional argument means it will take the value and assign it in a sequence 
- Default argument should be decalred after the positional argument, if we are going to define default argument before the positional argument, it will give us an error 

In [8]:
def add(x, y = 10):
    return x+y

In [9]:
add(1)
# Here x = 1 and y = 10

11

In [10]:
add(1,2)
# Here x = 1 and y = 2

3

In [12]:
def add(x = 1, y):
    return x+y

SyntaxError: non-default argument follows default argument (40711452.py, line 1)

In [11]:
add(1,2,3)

TypeError: add() takes from 1 to 2 positional arguments but 3 were given

In [13]:
def mul(x, y= 10 ,z):
    return x*y*z

SyntaxError: non-default argument follows default argument (2374642636.py, line 1)

In [15]:
def mul(x=1,y= 2, z = 3):
    return x*y*z

In [16]:
mul()
#Here x = 1, y = 2, z = 3

6

In [17]:
mul(10)
# Herer x = 10, y = 2, z = 3

60

In [18]:
mul(2,3)
#Here x = 2, y = 3, z = 3

18

In [19]:
mul(2,3,4)
#Here x = 2, y = 3, z=4

24

In [22]:
def div(x,y=1):
    return x//y

In [23]:
div(8,2)

4

In [24]:
div(16)

16

### 3. Keyworded arguments 

- When we assign any value to a variable in the function call, then it is known as keyworded arguments
- The value name(variable_name) for the keyworded argument should be same in both the function call as well as in the function decalartion
- For keyworded arguments the position or the order doesnot matter 
- Keyworded argument should be placed after the positional argument
- We can use positional argument, keyworded argument and default argument in only one order ->positional argument, keyworded argument, default argument

In [25]:
def course(a, b):
    print(a)
    print(b)

In [26]:
course('MCA',b = 'MBA')

MCA
MBA


In [27]:
course('MCA', c= 'B.Tech')

TypeError: course() got an unexpected keyword argument 'c'

In [28]:
course(b = 'MCA', a= 'B.Tech')

B.Tech
MCA


In [29]:
course(b ='MCA','MBA')

SyntaxError: positional argument follows keyword argument (3890548525.py, line 1)

In [36]:
# By chance if we have to use it follow point 4
def add(a,c, b= 10):
    return a+b+c

In [37]:
add(1,c=2)
#Here a = 1, c= 2, b = 10

13

In [38]:
def add(a,b= 10, c):
    return a+b+c

SyntaxError: non-default argument follows default argument (4225509078.py, line 1)

### 4. Variable length argument (*args)

- If we don't know the number of arguments that can be passed, then we will use a variable length argument
- We will use an asterik (*) before a variable
- It will store all the values inside a tuple (packing concept of tuples)
- It should be declared in the function definition 
- It should be placed after the positional argument

In [39]:
a = 1,2,3,4,5,6,7,8

In [40]:
print(a, type(a))

(1, 2, 3, 4, 5, 6, 7, 8) <class 'tuple'>


In [41]:
# Example without positional argument
def add(*a):
    sum = 0
    for i in a:
        sum = sum+i 
    return sum

In [42]:
add(1,2,3,4,5)

# Here all the values will be store in variable a as tuple
# I

15

In [43]:
# Example with postional argument
def mul(a, *c):
    m = a
    
    for i in c:
        m = m*i
    return m 

In [45]:
mul(1,2,3,4,5,6,7)
# Here a =1,c = (3,4,5,6,7)

5040

In [48]:
mul(a = 1,2,3,4,5,6,7)
# Here a =1,c = (3,4,5,6,7)

SyntaxError: positional argument follows keyword argument (1495071307.py, line 1)

### 5. Keyworded Variable length argument

- When we don't know how many keyworded argument are there, then we will use keyworded variable length argument
- It store the value as dictionary 
- The variable becomes the key and the values associated with the key will become the values for the keys

### Syntax:

    def function_name(**a):
        code 
        code

    function_name(key1 = value1, key2 = value2, key3 = value3.............)

In [49]:
def course(**a):
    print(a, type(a))

In [50]:
course(a='DS', b = "DSAI", c = 'DSML', d = 'DSAIML', e= "DSBFSI", f = 'DSMP')

{'a': 'DS', 'b': 'DSAI', 'c': 'DSML', 'd': 'DSAIML', 'e': 'DSBFSI', 'f': 'DSMP'} <class 'dict'>


### Anonymous Functions or Lambda Function 

- The functions where we don't give any name are called as anonymous function or lambda function
- __lambda__ keyword is used to declare an anonymous function 

    Syntax:
        
        (lambda parameter: operation) (arguments)

In [51]:
# create a lambda function that will going to add two numbers

(lambda x,y : x+y) (1,2)

3

In [52]:
def add(x,y):
    return x+y

#### we can assign a lambda() function to a variable and then we can call the variable n number of times

In [53]:
add = (lambda x,y:x+y)

In [54]:
add(1,2)

3

In [55]:
add(2,7)

9

In [56]:
add(9,10)

19

In [57]:
add(15, 16)

31

In [58]:
# Create a lambda function which will multiply 3 numbers 
mul = (lambda x,y,z : x*y*z)
mul(2,3,4)

24

In [63]:
# Create a lambda function that will take two argument and return the maximum among the two

a = (lambda x,y:x if x>y else y)

a(1,9)

9

In [66]:
# Create a lambda function that takes three value from the user and returns the min among the three

max_num = (lambda x,y,z:x if x<y and x<z else y if y<x and y<z else z)
max_num(1,2,0.5)

0.5

In [68]:
a=(lambda x,y,c : x if x<y else x<c or c )

a(2,1,3)

True

### Assignmnet Question 

In [70]:
# 3-D 
layer, number of list in layer and element in each list

import numpy as np
arr = np.random.randint(10,100, 12)
arr = arr.reshape(2,2,3)
arr

array([[[99, 12, 17],
        [48, 29, 47]],

       [[18, 71, 66],
        [44, 22, 69]]])

In [80]:
a = [] # store layer 
b = [] # store number of list
c = [] # store element inside list

for i in range(2):
    for j in range(3): 
        for k in range(4): 
            c.append(i+j+k)
        b.append(c)
        c = [] # Cleaned the c list so that it can store next elemnts of the next list
    a.append(b)
    b= [] # cleaning the b list so that it can store layer 


In [81]:
print(a)

[[[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]], [[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]]]


In [82]:
arr = np.array(a)

In [83]:
arr

array([[[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]]])

In [86]:
# 2-D

import numpy as np
arr = np.random.randint(10,100, 12)
arr = arr.reshape(3,4)
arr

array([[25, 58, 48, 78],
       [18, 38, 41, 70],
       [75, 96, 92, 27]])