### Numpy 

- Numpy is a Python library, we call it a Python library because it supportsd python syntax
- Numpy stands for Numerical Python 
- Numpy is used to perform advanced numerical computation on larger dataset
- By using numpy, we can perform complex operations with less lines of code 
- Numpy provides a very useful data-structure known as __Array__

### How to import Numpy ?

In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [3]:
lst = [1,2,3,4,5]
print(lst,type(lst))

[1, 2, 3, 4, 5] <class 'list'>


In [4]:
a = np.array(lst)
print(a, type(a))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
a.ndim

1

### Version 

In [6]:
np.__version__

'1.24.3'

### How to install numpy ?

In [7]:
pip install Numpy

##### conda update numpy in the anaconda prompt

### Array 

- An array is a collection of homogenous elements (same datatype elements)

In [8]:
lst = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
type(arr)

numpy.ndarray

### List vs Array 

- With the help of array, we can easily perform some operations that we could not easily perform over the list 
- Arrays are faster as compared to the list

In [10]:
lst = [i for i in range(1,11)]
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
# Multiple each element of this list with a number

for i in range(len(lst)):
    lst[i] *= 5

print(lst)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [13]:
# multiple each element of the array with a number

lst = [i for i in range(1,11)]
arr = np.array(lst)
arr = arr*5
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

### Array are faster than list

In [14]:
import time 

In [15]:
st = time.time()

lst = [i*5 for i in range(100000)]

end = time.time()

tt = end-st
print(tt)

0.005502462387084961


In [16]:
st = time.time()

arr = np.arange(100000)
arr = arr*5

end = time.time()

tt = end-st
print(tt)

0.002833843231201172


### Why arrays are faster than a list?

- On list, we have to use loop to perform some operation over it
- Loops makes the process slow 
- Arrays use vectorised operation by using array broadcasting and this process is much faster than loops
- A list is a collection of heterogenous elements
- A list has to store a lot of information for each element seperately because each element behaves differently in a list
- This is the main reason that makes the process slow
- An array is a collection of homogenous elements, it does not store extra information for each element seperately

In [ ]:
v = (ai+bj+ck)*5
v = (ai+bj+ck)*(5i+5j+5k)
v = (5a, 5b, 5c)

i.i = 1, j.j = 1, k.k = 1 but i.j = 0, j.k = 0 i.k = 0

### Array upcasting

- When we pass heterogeous elements in an array, then it converts all the elements to one datatype and this process is called array upcasting

##### int<float<complex<string<object

In [17]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr = np.array([1,2.0,3,4,5])
arr

array([1., 2., 3., 4., 5.])

In [20]:
arr.dtype

dtype('float64')

In [21]:
arr = np.array([1,2.0,3+9j,4,5])
arr

array([1.+0.j, 2.+0.j, 3.+9.j, 4.+0.j, 5.+0.j])

In [22]:
arr.dtype

dtype('complex128')

In [24]:
arr = np.array([1,2.0,3+9j,'4',5])
arr

array(['1', '2.0', '(3+9j)', '4', '5'], dtype='<U64')

In [25]:
arr.dtype

dtype('<U64')

In [26]:
arr = np.array([1,2.0,3+9j,'4',5], dtype = object)
arr

array([1, 2.0, (3+9j), '4', 5], dtype=object)

In [27]:
for i in arr:
    print(i, type(i))

1 <class 'int'>
2.0 <class 'float'>
(3+9j) <class 'complex'>
4 <class 'str'>
5 <class 'int'>


In [28]:
arr.dtype

dtype('O')

### Creating different kinds of array 

### np.arange()

- it creates an array of numbers

Syntax:
        
        np.arange(start, stop, step_size)
        stop value - excluded
        step-size = 1

In [32]:
# Create an array that has number for 1 to 10

arr = np.arange(1,11,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
lst = [i for i in range(1,11,1)]
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### np.linspace

- It creates an array of equally spaced values within a range of values 

Syntax:
    
    np.linspace(start, stop, number of values)
    
    By default, in linspace both my start and stop are included 
    By default, linspace will return the answer in float

In [34]:
# Create an array of 5 elements equally spaced from each other between 1 and 3

arr = np.linspace(1,3,5)
arr

array([1. , 1.5, 2. , 2.5, 3. ])

In [35]:
# Create an array of 50 elements equally spaced from each other between 1 and 3

arr = np.linspace(1,3,50)
arr

array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

In [36]:
1.08163265-1.04081633

0.04081632000000002

In [37]:
1.04081633-1

0.040816329999999956

In [38]:
# Create an array of 50 elements equally spaced from each other between 1 and 100

arr = np.linspace(1,100,50)
arr

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

### np.zeros

- It returns an array of the given shape where all the elements in the array are zeros 

Syntax:
    
    np.zeros((row, column))
    
    By default, it will return answer in flaot

In [45]:
# create a 3*3 matrix (3 rows and 3 columns) having all the values as 0 

arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
arr = np.zeros((3,3), dtype = int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### np.ones

- It returns an array of the given shape where all the elements in the array are ones

Syntax:
    
    np.ones((row, column))
    
    By default, it will return answer in flaot

In [47]:
# Create a 4*3 matrix with all the elements inside the array as 1's

arr = np.ones((4,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
arr = np.ones((4,3), dtype = int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### np.full()

- It returns an array of the given shape and a given a value 

Syntax:
    
    np.full((rows, column), value)

In [49]:
# create a 3*3 matrix having all the elements value as 5

arr = np.full((3,3), 5)
arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [50]:
arr = np.full((3,3), 5.0)
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [51]:
arr = np.full((3,3), 5.0+9j)
arr

array([[5.+9.j, 5.+9.j, 5.+9.j],
       [5.+9.j, 5.+9.j, 5.+9.j],
       [5.+9.j, 5.+9.j, 5.+9.j]])

In [55]:
# create a 3*3 matrix having all the values a 5

arr = (np.ones((3,3), dtype = int))*5
arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### np.eye()

- It returns an identity matrix
- In a an identity matrix, the diagonal's elements are going to 1's and the non-diagonal elements are 0's

Syntax:
    
    np.eye(rows, columns)

In [56]:
arr = np.eye(4,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [57]:
# create a 4*4 identity matrix

arr = np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
# create a 4*4 identity matrix

arr = np.eye(4,4, dtype = int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### np.zeros_like()

- It will return an array of 0's of the given shape


In [64]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr = np.zeros_like(arr)
arr

array([[0, 0, 0],
       [0, 0, 0]])

### np.ones_like()

- It will return an array of 1's of the given shape

In [67]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr1 = np.ones_like(arr)
arr1

array([[1, 1, 1],
       [1, 1, 1]])

### np.full_like()

- It will return an arry of the given shape and a given value

Syntax:
        
        np.full_like(arr, value)

In [70]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr = np.full_like(arr, 6)
arr

array([[6, 6, 6],
       [6, 6, 6]])

### np.diagonal()

- It returns the prinicpal diagonal from an array 

In [75]:
arr = np.random.randint(10,100,36)
arr

array([35, 25, 83, 60, 75, 33, 90, 60, 52, 37, 43, 40, 80, 40, 40, 22, 70,
       29, 30, 92, 14, 22, 53, 86, 19, 96, 82, 20, 13, 30, 13, 83, 89, 78,
       51, 14])

In [76]:
arr = arr.reshape(6,6)
arr

array([[35, 25, 83, 60, 75, 33],
       [90, 60, 52, 37, 43, 40],
       [80, 40, 40, 22, 70, 29],
       [30, 92, 14, 22, 53, 86],
       [19, 96, 82, 20, 13, 30],
       [13, 83, 89, 78, 51, 14]])

In [77]:
z = np.diagonal(arr)
z

array([35, 60, 40, 22, 13, 14])

In [80]:
z = np.diagonal(arr, offset = 2)
z

array([83, 37, 70, 86])

In [81]:
z = np.diagonal(arr, offset = -3)
z

array([30, 96, 89])

### np.diag()

- it returns a diagonal array 
- in a diagonal array, the diagonals are non -zero elements rest every element is a zero

Syntax:

    np.diag(elements that i want to have as diagonals)

In [82]:
arr = np.diag([1,2,3,4,5,6,7])
arr

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [83]:
arr = np.random.randint(10,100,25).reshape(5,5)
arr

array([[17, 98, 56, 84, 93],
       [60, 80, 39, 61, 66],
       [10, 53, 13, 54, 16],
       [22, 28, 37, 28, 18],
       [24, 83, 78, 84, 98]])

In [85]:
arr1 = np.diag(np.diagonal(arr))
arr1

array([[17,  0,  0,  0,  0],
       [ 0, 80,  0,  0,  0],
       [ 0,  0, 13,  0,  0],
       [ 0,  0,  0, 28,  0],
       [ 0,  0,  0,  0, 98]])

### np.trace()

- It returns the sum of the diagonal elements 

In [86]:
arr = np.random.randint(10,100,25).reshape(5,5)
arr

array([[34, 30, 93, 56, 25],
       [79, 78, 25, 21, 28],
       [51, 94, 98, 65, 87],
       [61, 97, 48, 76, 23],
       [71, 50, 98, 21, 25]])

In [93]:
a = np.trace(arr, offset = -1)
a

242

In [95]:
b = np.diagonal(arr, offset = -1).sum()
b

242

### Attributes 

- These are the characterstics or properties of an object, which are storing some kind of information in them 

### Shape 

- This tells us about the shape of array 

In [96]:
arr = np.random.random(24) # random.random will generate 24 values between 0 and 1
arr

array([0.47363352, 0.00424235, 0.83333729, 0.44979177, 0.12925194,
       0.38898215, 0.87866394, 0.18669305, 0.06764751, 0.56196286,
       0.10056544, 0.86849104, 0.89109507, 0.90266816, 0.10893365,
       0.42899936, 0.72446588, 0.39502107, 0.39672511, 0.78569699,
       0.10266587, 0.94489799, 0.97297604, 0.91601493])

In [99]:
arr.shape

(24,)

In [100]:
arr = np.random.randint(10,100,25).reshape(5,5)
arr

array([[60, 22, 96, 51, 76],
       [21, 65, 65, 28, 23],
       [68, 77, 27, 46, 72],
       [94, 32, 99, 13, 23],
       [71, 48, 96, 97, 39]])

In [101]:
arr.shape

(5, 5)

### Reshape 

- It reshapes an array as per the given shape 
- It returns a new array of the given shape, it does not make any changes in the existing array

In [105]:
arr = np.random.random(25) # random.random will generate 24 values between 0 and 1
arr

array([0.98369635, 0.54550894, 0.709021  , 0.91411086, 0.93198367,
       0.4779879 , 0.48964756, 0.89161001, 0.4753533 , 0.44447413,
       0.13837145, 0.74412783, 0.22506871, 0.3669813 , 0.36334451,
       0.84865891, 0.13664072, 0.82461803, 0.49775566, 0.05762445,
       0.77416594, 0.86271795, 0.04049603, 0.87188003, 0.86627779])

In [106]:
arr.shape

(25,)

In [107]:
arr1 = arr.reshape(5,5)
arr1

array([[0.98369635, 0.54550894, 0.709021  , 0.91411086, 0.93198367],
       [0.4779879 , 0.48964756, 0.89161001, 0.4753533 , 0.44447413],
       [0.13837145, 0.74412783, 0.22506871, 0.3669813 , 0.36334451],
       [0.84865891, 0.13664072, 0.82461803, 0.49775566, 0.05762445],
       [0.77416594, 0.86271795, 0.04049603, 0.87188003, 0.86627779]])

In [108]:
arr1.shape

(5, 5)

In [109]:
arr1 = arr.reshape(5,6)
arr1

ValueError: cannot reshape array of size 25 into shape (5,6)

In [110]:
arr = np.random.random(12) # random.random will generate 24 values between 0 and 1
arr

array([0.49111611, 0.73049864, 0.70656864, 0.72034008, 0.21436307,
       0.40092756, 0.33007038, 0.29142874, 0.16515129, 0.34797384,
       0.21459067, 0.15660914])

In [116]:
arr.shape

(12,)

In [117]:
arr.ndim

1

In [111]:
arr1 = arr.reshape(2,6)
arr1

array([[0.49111611, 0.73049864, 0.70656864, 0.72034008, 0.21436307,
        0.40092756],
       [0.33007038, 0.29142874, 0.16515129, 0.34797384, 0.21459067,
        0.15660914]])

In [112]:
arr2 = arr.reshape(3,4)
arr2

array([[0.49111611, 0.73049864, 0.70656864, 0.72034008],
       [0.21436307, 0.40092756, 0.33007038, 0.29142874],
       [0.16515129, 0.34797384, 0.21459067, 0.15660914]])

In [113]:
arr3 = arr.reshape(6,2)
arr3

array([[0.49111611, 0.73049864],
       [0.70656864, 0.72034008],
       [0.21436307, 0.40092756],
       [0.33007038, 0.29142874],
       [0.16515129, 0.34797384],
       [0.21459067, 0.15660914]])

In [114]:
arr4 = arr.reshape(2,3,2)
arr4

array([[[0.49111611, 0.73049864],
        [0.70656864, 0.72034008],
        [0.21436307, 0.40092756]],

       [[0.33007038, 0.29142874],
        [0.16515129, 0.34797384],
        [0.21459067, 0.15660914]]])

In [115]:
arr4.ndim

3

### dtype 

- This tells us about the datatype stored in the array 

In [118]:
arr

array([0.49111611, 0.73049864, 0.70656864, 0.72034008, 0.21436307,
       0.40092756, 0.33007038, 0.29142874, 0.16515129, 0.34797384,
       0.21459067, 0.15660914])

In [119]:
arr.dtype

dtype('float64')

In [120]:
arr = np.random.randint(10,100,25).reshape(5,5)
arr

array([[30, 59, 30, 82, 83],
       [17, 79, 83, 50, 55],
       [30, 61, 76, 23, 64],
       [13, 75, 37, 52, 21],
       [16, 80, 65, 30, 57]])

In [121]:
arr.dtype

dtype('int32')

### Dimensionality 

- This tells us about the dimension of an array

In [122]:
arr = np.random.random(12) # random.random will generate 24 values between 0 and 1
arr

array([0.15497821, 0.0976501 , 0.91140478, 0.68528132, 0.23659293,
       0.89616887, 0.33098804, 0.76637801, 0.44612253, 0.15492973,
       0.36875698, 0.32637817])

In [123]:
arr.ndim

1

In [124]:
arr = np.random.randint(10,100,25).reshape(5,5)
arr

array([[26, 36, 65, 16, 68],
       [35, 85, 60, 27, 97],
       [14, 55, 96, 86, 54],
       [25, 39, 14, 10, 60],
       [81, 43, 80, 71, 66]])

In [125]:
arr.ndim

2

In [126]:
arr = np.random.randint(10,100,36).reshape(2,3,6)
arr

array([[[32, 98, 11, 87, 80, 49],
        [18, 90, 30, 35, 63, 35],
        [88, 21, 45, 82, 87, 51]],

       [[45, 38, 45, 23, 38, 79],
        [21, 94, 85, 20, 40, 86],
        [91, 69, 46, 15, 73, 19]]])

In [127]:
arr.ndim

3

### Create a 1-D array, 2D array and 3D array 

list -- 1D array 
list of a list or 2 1D array ---- 2D
2 2D --- 3D
2 3D --- 4D

In [129]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [130]:
a.ndim

1

In [131]:
b = np.array([[1,2,3], [3,4,5]])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [132]:
b.ndim

2

In [133]:
c = np.array([[[1,2,3],[3,4,5]],
              [[4,5,6], [6,7,8]]])
c

array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 6],
        [6, 7, 8]]])

In [134]:
c.ndim

3

In [135]:
c.shape

(2, 2, 3)

In [137]:
d = c.reshape(3,2,2)
d

array([[[1, 2],
        [3, 3]],

       [[4, 5],
        [4, 5]],

       [[6, 6],
        [7, 8]]])

In [138]:
d.ndim

3

In [139]:
d.shape

(3, 2, 2)

In [146]:
a = np.array([[[1,2,3,4], [4,5,6,7]],
     [[1,2,3,5], [4,5,6,8]]])

In [147]:
a

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 5],
        [4, 5, 6, 8]]])